"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
//import * as uuid from "uuid";
var v4_1 = require("./node_modules/uuid/dist/cjs/v4");
var abc = "halit";
console.log(abc);
var a = 10;
console.log(a);
var id = (0, v4_1.default)();
console.log(id);
